# Generated by Django 3.1.1 on 2020-10-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertransaction',
            old_name='transactions_id',
            new_name='transaction_id',
        ),
    ]
